*** Settings ***

Documentation     Defines all resources and keywords 
...               handling the Activation object
...
...  

*** Variables ***

*** Keywords ***

Begin
    # Click Element    name
    No Operation
    Log    Keyword 'Activation.Begin' not implemented in ${SUITE_NAME}   WARN

Enter Reason
    No Operation
    Log     Keyword 'Activation.Enter Reason' not implemented in ${SUITE_NAME}   WARN


